services:
  api:
    build:
      context: .
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/usr/app/
    container_name: dock-banking-api
    links:
      - db

  unit-test:
    build:
      context: .
    command: go test -v ./...
    volumes:
      - .:/usr/app/
    container_name: dock-banking-unit-test
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /path/to/postgres/database-data:/var/lib/postgresql/data/
